In [1]:
import numpy as np

In [2]:
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(4,3))
x3 = np.random.randint(10, size=(2,3,4))

In [3]:
x1

array([7, 1, 8, 7, 7, 6])

In [4]:
x2

array([[9, 6, 3],
       [8, 1, 7],
       [5, 5, 7],
       [4, 3, 5]])

In [5]:
x3

array([[[5, 5, 5, 5],
        [5, 1, 0, 8],
        [3, 8, 7, 2]],

       [[4, 5, 5, 4],
        [4, 8, 3, 3],
        [2, 5, 4, 3]]])

In [6]:
print(x3.ndim)

3


In [8]:
print(x2.ndim)

2


In [9]:
print(x2.shape)

(4, 3)


In [10]:
print(x3.shape)

(2, 3, 4)


In [11]:
print(x1.shape)


(6,)


In [12]:
print(x1.size)

6


In [13]:
print(x2.size)

12


In [14]:
print(x3.size)

24


In [15]:
x1.dtype

dtype('int32')

In [16]:
x3.dtype

dtype('int32')

In [17]:
x2.itemsize

4

In [18]:
x3.nbytes

96

#### for indexing 

In [20]:
print(x1[0])

7


In [28]:
print(x2[2,1])

5


In [30]:
print(x2[2,-1])

7


##### updating value

In [32]:
x2 [2,-1] = 3.14159
print(x2[2,-1])

3


In [35]:
x = np.arange(10)

In [36]:
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [38]:
print("x[7:3:-1] =" , x[7:3:-1])

x[7:3:-1] = [7 6 5 4]


In [39]:
print(x2)

[[9 6 3]
 [8 1 7]
 [5 5 3]
 [4 3 5]]


#### printing 2 dimentional 

In [40]:
print(x2[:3,:2])

[[9 6]
 [8 1]
 [5 5]]


In [41]:
print(x2[::2,:])

[[9 6 3]
 [5 5 3]]


In [42]:
x2[1,:]

array([8, 1, 7])

#### reshaping array

In [47]:
z =np.arange(1,10)

In [51]:
z

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
z.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
z.reshape(4,4)

ValueError: cannot reshape array of size 9 into shape (4,4)

In [55]:
x = np.array([1,2,3])
y = np.array([4,5,6])
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [57]:
z = np.array([7,8,9])
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
arr2d =np.array([1,2,3],
                [4,5,6])
np.concatenate([arr2d,arr2d])

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [62]:
x = [1,2,3,4,5,6,7,8,9]
x1,x2,x3 = np.split(x,[3,5])

In [64]:
 %time print(x1,x2,x3)

[1 2 3] [4 5] [6 7 8 9]
CPU times: total: 0 ns
Wall time: 980 μs


In [66]:
theta = np.linspace(0,np.pi,3)
theta

array([0.        , 1.57079633, 3.14159265])

In [68]:
print("sin(theta)= :" , np.sin(theta))

sin(theta)= : [0.0000000e+00 1.0000000e+00 1.2246468e-16]
