In [7]:
import pandas as pd
import numpy as np

In [8]:
rng = np.random.RandomState(42)

In [11]:
A =pd.DataFrame(rng.randint(0,20,(2,2)),columns = list('AB'))
A


A  B
0  10  3
1   7  2

In [12]:
B=pd.DataFrame(rng.randint(0,10,(3,3)),columns = list('BAC'))
B

B  A  C
0  5  4  1
1  7  5  1
2  4  0  9

In [13]:
A+B

A    B   C
0  14.0  8.0 NaN
1  12.0  9.0 NaN
2   NaN  NaN NaN

In [15]:
A.add(B,fill_value=0)

A    B    C
0  14.0  8.0  1.0
1  12.0  9.0  1.0
2   0.0  4.0  9.0

In [16]:
A = rng.randint(10, size=(3,4))

In [17]:
A


array([[5, 8, 0, 9],
       [2, 6, 3, 8],
       [2, 4, 2, 6]])

In [18]:
A-A[0]

array([[ 0,  0,  0,  0],
       [-3, -2,  3, -1],
       [-3, -4,  2, -3]])

In [19]:
df = pd.DataFrame(A, columns = list('QRST'))
df

Q  R  S  T
0  5  8  0  9
1  2  6  3  8
2  2  4  2  6

In [20]:
df- df.iloc[0]

Q  R  S  T
0  0  0  0  0
1 -3 -2  3 -1
2 -3 -4  2 -3

In [22]:
df.subtract(df['S'],axis =0)

Q  R  S  T
0  5  8  0  9
1 -1  3  0  5
2  0  2  0  4

In [23]:
vals1 = np.array([1,None,3,4])
vals1

array([1, None, 3, 4], dtype=object)

In [24]:
vals2 = np.array([1,np.nan,3,4,])
vals2

array([ 1., nan,  3.,  4.])

In [25]:
1+np.nan

nan

In [26]:
0*np.nan

nan

In [27]:
vals2.sum(), vals2.min(), vals2.max()

(nan, nan, nan)

In [28]:
np.nansum(vals2), np.nanmin(vals2), np.nanmax(vals2)

(8.0, 1.0, 4.0)

### operating on NULLvalues

In [29]:
import pandas as pd
import numpy as np

In [30]:
data = pd.Series([1,np.nan, 'hello' , None])
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [31]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [32]:
data.isnull().sum()

2

In [33]:
data[data.notnull()]

0        1
2    hello
dtype: object

In [34]:
data.dropna()

0        1
2    hello
dtype: object

In [35]:
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [37]:
data.dropna(inplace=True)

In [38]:
data

0        1
2    hello
dtype: object

In [42]:
data.reset_index()

index      0
0      0      1
1      2  hello

In [44]:
df =pd.DataFrame([[1, np.nan, 2],
                [2,3,5],
                [np.nan,4,6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [45]:
df.dropna()

0    1  2
1  2.0  3.0  5

In [51]:
df.dropna(inplace=True)

In [52]:
df.reset_index()

index    0    1  2
0      1  2.0  3.0  5

In [53]:
df.dropna(axis='columns')

0    1  2
1  2.0  3.0  5

In [54]:
df =pd.DataFrame([[1, np.nan, 2],
                [2,3,5],
                [np.nan,4,6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [55]:
df.dropna(axis=1)

2
0  2
1  5
2  6

In [56]:
df =pd.DataFrame([[1, np.nan, 2],
                [2,3,5],
                [np.nan,4,6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [57]:
df[3] = np.nan
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [58]:
df.dropna(axis='columns', how = 'all')

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [59]:
df.dropna(axis='columns', thresh =3)

2
0  2
1  5
2  6

In [62]:
df.fillna(5)

0    1  2    3
0  1.0  5.0  2  5.0
1  2.0  3.0  5  5.0
2  5.0  4.0  6  5.0

##### ffill and bfill is front fill and back fill

In [63]:
data.fillna(method='ffill')

C:\Users\nimad\AppData\Local\Temp\ipykernel_20288\1844443866.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='ffill')


0        1
2    hello
dtype: object

In [65]:
data.fillna(method=('bfill'))

C:\Users\nimad\AppData\Local\Temp\ipykernel_20288\612052917.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method=('bfill'))


0        1
2    hello
dtype: object